### ISSUE TITLE
Telegrams Notifical is not work 

### ISSUE THREAD

**Issue by tontheonelove** [DeviaVir/zenbot#1252]
I try config it  is notwork    Who have Tutorial ot Method Please Helpme  

My Config

// telegram configs
c.notifiers.telegram = {};
c.notifiers.telegram.on = true // false telegram disabled; true telegram enabled (key should be correct)
c.notifiers.telegram.bot_token = 'AAFkK11XXXXXXXXXXAJSy8Kh2w54U'
c.notifiers.telegram.chat_id = '528809475' // the id of the chat the messages should be send in
// end telegram configs

###  Is Error Code  When  bot is Buy Or Sale

{"ok":false,"error_code":404,"description":"Not Found"}

Thankyou Verymuch

**Comment by rcoenen** [comment]
works for me

**Comment by defkev** [comment]
> 404

Invalid token?

**Comment by tontheonelove** [comment]
@rcoenen @defkev 

My token is Generator by   Fatherbot Telegram   Sir  i see chat id  & Token

"   You can use this token to access HTTP API:
528809475:AAFkK11oHEyGJxxxxxbHgHWAJSy8Kh2w54U

For a description of the Bot API, see this page: https://core.telegram.org/bots/api "



  and i test getMe method  message is show 
 " {"ok":true,"result":{"id":528809475,"is_bot":true,"first_name":"vipbot","username":"vipxxx_bot"}}"


i think my chat id & my bot token  is all right   but when  me config on conf.js  is not work   

Who have tutorial  please help me  


Thankyou Verymuch

**Comment by andan02** [comment]
I also tried the getme for my id - clubzen_bot.  I got the same result.  This isnt working for me either.  please advise

**Comment by andan02** [comment]
pushover is working fine however

**Comment by andersontarj** [comment]
Hey guys... 
The process of setting the telegram for sending msg was very simple after analyzing how it works, mine is working normally.
 Follows example msg in smartphone.
Buy: 
ZenbotMSG:
Buy BINANCE: 
buy order completed at 2018-02-19 08:26:18:

0.00202988 BTC at 10886.80 USDT
total 22.0988 USDT
0.0000% slippage (orig. price 10886.80 USDT)
execution: a few seconds
--------------------------------------------
Sell:
ZenbotMSG:
Sell BINANCE: 
sell order completed at 2018-02-19 09:08:18:

0.00202925 BTC at 10979.49 USDT
total 22.2801 USDT
0.0000% slippage (orig. price 10979.49 USDT)
execution: a few seconds

My step-by-step Telegram configuration for sending MSG in transactions 
-------------------------------------------------- ------- 
1 - No telegram added the Bot Father = @BotFather 

2 - After adding the same cry a new bot with the command /newbot 

3 - Give a name for it. Ex: AlertTraderZB 

4 - Repeat the name and add no end to the _bot extension. Ex: AlertTraderZBot or AlertTraderZB_bot 
4.1 - Without BotFather run the / mybots command to list the or your bots. 
4.2 - Click on the created bot and click "Edit Bot" and make as edits for Name, Description, About, Botpic (photo) and Commands are not necessary. 
4.3 - Under "Bot Settings" click "Allow Groups?" and select "Disconnect groups" and under "Group privacy" select "Disconnect" 
4.4 - With your choice and Internet access, click "Back to Bot" and then "Back to Bot List" 
4.5 - Click on your bot and then "Here it is: AlertTraderZB @AlertTraderZB_bot" to open your button and click "START" 
4.6 - Ready the bot is ready to receive alerts. 

5 - Room it will generate your HTTP API which is similar to this. API: 534764613: AAEwjkcrWpOkSmqSq5NzG9zMBFwchjAUuwU 

6 - Now add the "Get ID" button to get your chat ID = @get_id_bot 

7 - Within the Get ID if it is not your Chat ID automatically type /start and copy your chat ID 

8 - Now edit the file "Conf.js" again vim conf.js 

9 - Locate the Telegram command with the command: /c.notifiers.telegram 
9.1 - Change the settings and leave as below: c.notifiers.telegram.on = true c.notifiers.telegram.bot_token = '534764613: AAEwjkcrWpOkSmqSq5NzG9zMBFwchjAUuwU' c.notifiers.telegram.chat_id = '192573714' Warning: Do not use TOKEN or CHAT_ID because it has already been deleted 

10 - Save and close and test with a test trade to see if it has been received as msg on your bot. ex: ./zenbot.sh trade --paper --conf ./conf.js

**Comment by tontheonelove** [comment]
Thankyou Verymuch  Friend   i ReConfig  again   is work   ^_^
