### ISSUE TITLE
machine learning?

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#128]
Does this perform any machine learning / artificial neural network function? Prior README commits show it definitely did this at some point, current iteration doesn't directly mention this being a feature. I've looked through the code and admittedly am not great with node, but it appears that the trade logic is completely hard coded and the zenbrain library, map and reduce, simply pulls in data for one to manually run the simulator. 

Is my understanding correct and if so does anyone know why this changed?

**Comment by BarnumD** [comment]
I think you are correct and that carlos8f took the functionality out
temporarily.  But then he mentioned being in jail and hasn't been seen for
a while.

**Comment by Camille92** [comment]
Indeed the last trace of activity I can find of him is traced back in September.

However the bot is definitely branded as IA driven so I'm not sure. (I don't use it, just curious about the project).

**Comment by 7flash** [comment]
Can I use 2.0 version with machine learning?

**Comment by carlos8f** [comment]
Originally the idea for zenbot was to exclusively use machine learning, but the neural network part never panned out. As far as I have found, there really isn't a practical pure neural network model for trading, at least unless you want to pull in the price of gold and speculate on a thousand other variables. So in that way I made a mistake on the branding of it :) The machine learning code was pulled because I moved from a volume-sensing strategy to an RSI-based one, and the volume strategy required constant machine learning to run. With RSI being a simple bounded indicator, one-size-fits-all config replaced the learned variables.

Default strategy in 4.x will (tentatively) require at least one unbounded variable, and I may write a "tuner" that will find some optimal configuration, but the tuner won't have to run constantly for trading to work, one might run it every few months or so.

**Comment by 7flash** [comment]
You are thinking about role of machine learning in this case as analog for similar functionality to find the best parameters for strategy in Meta Trader?

**Comment by 7flash** [comment]
How about something especially now?
Could we analyze all history, find fractals and patterns and try to use only them without realtime indicators?

**Comment by carlos8f** [comment]
@7flash I suppose so, although I haven't used Meta Trader. Machine learning would automate the process of mutation of params, and looping of sims. Not a neural network, but a trainer.

**Comment by carlos8f** [comment]
> Could we analyze all history, find fractals and patterns and try to use only them without realtime indicators?

See above, I don't know of a practical way to do this. Neural networks can be built, but require a huge amount of data and is far beyond the scope of what I'm doing. And in theory, some basic technical analysis should perform as good as a fancy neural network, and require way less resources.
