### ISSUE TITLE
Is 4.x still planned for release?

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#134]
Is this project maintained anymore and is 4.x still planned for release?

**Comment by papacasper** [comment]
Looks to me that it is still in development. On the [4.x](https://github.com/carlos8f/zenbot/tree/4.x) branch there has been some recent commits.

**Comment by laoyaoshine** [comment]
The great spirit filling expectation

**Comment by l0rdh3lix** [comment]
Seems like development slowed down but didn't stop. TBH I was worried since jail was mentioned in another thread. I'm excited for v.4!

**Comment by zfsamzfsam** [comment]
+1

**Comment by carlos8f** [comment]
Yep, 4.x is in active development as of 2 weeks ago.

The 3.x trading model, developed last year and based on short term RSI movements, simple trading frequency limits, and market orders, I found to be pretty sub-optimal in the current market conditions. It may have been profitable then, but now it underperforms vs. buy-hold, and market order fees end up making for negative profit in the long term.

I decided to rewrite the whole thing, and I have a tentative trading strategy that beats the old RSI method, and beats buy/hold, and will focus on limit orders rather than market, so trade fees adding up will not be an issue. The new program will be in theory pretty lightweight, and won't require loads of historical data processing to run the trader. Also exchange implementation code will be in other repos, since I don't have the bandwidth to maintain it in core.

I hope to drop 4.0-beta1 within the next couple weeks.

**Comment by ghost** [comment]
@carlos8f awesome, great to see your back and working on this again. BTC just hit 1400 on gdax! Exciting times to be a crypto trader. Usually indicators like rsi are lagging and will not perform well in most markets long term especially in up trending markets like bitcoin and s&p. Looking forward to the next update to test out.

**Comment by zfsamzfsam** [comment]
Hope to support ES6 & TypeScript2 in zenbot 4.x

**Comment by carlos8f** [comment]
Zenbot 4 is out! Do give it a try and join the Discord channel I just started: https://discord.gg/ZdAd2gP
