### ISSUE TITLE
[Feature Request] Notifier Interaction

### ISSUE THREAD

**Issue by LoneWolf345** [DeviaVir/zenbot#1550]
### Describe the Feature
I would like the ability to "Talk" to zenbot through a connected notifier.  If, for example, I have discord configured with zenbot I would like to send the message "What are my current balances for Binance" and have it respond with all my current holdings.  Also have things like switching to manual mode so that it will stop trading.  There are many other examples as you can imagine.  But the first step is to create that framework.

**Comment by tuxitor** [comment]
@LoneWolf345 
What you ask for and a lot more are actually done in another fork, but a lot of water have flooded into the ocean since then. You may look at this to get an idea:

https://github.com/tuxitor/zenbot/blob/zentalk/docs/Zentalk.md

"The Zentalk Concept" actually worked pretty well at that time, except maybe for auto websockeet address:port on systems other than Linux This work was done before any serious notifier system was implemented in Zenbot, but now a lot of those notifiers are implemented in a fashion that ZenTalk doesn't fit into.

If someone is interested in following up on this, "The Zentalk Concept" is still living in the zentalk branch here: https://github.com/tuxitor/zenbot/tree/zentalk
