### ISSUE TITLE
MongoDB timeouts on Mac OS X, auto-respawn possible?

### ISSUE THREAD

**Issue by orcinus** [DeviaVir/zenbot#167]
No idea what changed, but ever since checking out 4.0, i keep getting mongo timeouts when trying to do a backfill. I've tried debugging it a bit, but can't figure out what's wrong. Mongo appears to be working fine.

Increasing timeouts (via connectTimeoutMS and socketTimeoutMS parameters in the connection string/URI) does not help. I can't even go through a single day of backfill without at least 3-4 timeouts.

Would it be possible to make backfill (and other modules) auto-respawn on DB timeout instead of just dying with an unhandled exception?

**Comment by carlos8f** [comment]
I ran into the same thing, fix incoming. Also patching Poloniex backfill problem that causes gaps in the data.

**Comment by rrodrigu3z** [comment]
Awesome, I've just cloned the repo to give it a try and I'm having the same problem too :(

**Comment by betmoar** [comment]
Try changing the args.start and args.end to 2 hours (7200) instead of 24 hour and the Polo backfill should work without issues.

**Comment by carlos8f** [comment]
@pilldriver I originally had 2 hours, experimented with different ranges, and found that some coins have gaps where there is only 1 trade returned from the query (very strangely), which causes the backfiller to loop or finish prematurely. Since then I changed polo's backfiller to work backwards instead of forwards (because of gaps in the data if result size overflows 50k), so maybe that fixed the issue and I can set it back down to 2 hours.

**Comment by betmoar** [comment]
On heavy traded coins like XRP / ETH i noticed there are sometimes more then 50k trades in a timespan of 2 hours (crazy) so maybe it should even loop on a hourly basis or add a param like --span on the backfill part? Guess backward is the proper way to loop over the data. A gap fixer would be a nice addition the fill in the blanks when the polo api gives unstable output.

**Comment by carlos8f** [comment]
50k trades in 2 hours is ok, if backfilling backwards. I found (the hard way) that their limit query actually is sorted descending.

I've been dreaming of a gap filler since zb 2.x, lol, but it's a hard thing to make. it's hard to know when there are gaps, if any. So I came up with the resume markers in 4.x, which at least mean you rarely have to download the same trade twice (in theory).

**Comment by carlos8f** [comment]
in other news, BTC just hit 2099.59 USD on gdax, omg 🎉

**Comment by betmoar** [comment]
A gap filler should be easier to code when the candles are saved in minutes instead of individual trades. (in theory)

Now when there is a gap between the oldest_time and newest_time its almost impossible to detect what is missing.

Anyway great bot, just getting the feeling of it :)

**Comment by carlos8f** [comment]
fixed with aae2137956f2d9922e3ffd3517dba1f233e3a00e

@pilldriver glad to have you onboard, be sure to try v4.0.2 if you haven't, it includes a new concept to filter out weak signals, using a std deviation filter. A must-have for poloniex since it will reduce fees from whipsaws. working pretty well so far with my tests.

also I'm going to try to get the Zenbot discord chat going again. crypto coin community is back!
