### ISSUE TITLE
Poloniex error

### ISSUE THREAD

**Issue by crack00r** [DeviaVir/zenbot#289]
{ error: 'Nonce must be greater than 149751797808900. You provided 149751797757300.' }

Poloniex API is down! unable to call getBalance, retrying in 10s
ggetBalance error:
{ error: 'Nonce must be greater than 149751800105300. You provided 149751799605200.' }

**Comment by FreshLondon** [comment]
duplicate log of issue #193

**Comment by crack00r** [comment]
@CreativeBacon did you get it fixed?
may you publish your file?

**Comment by FreshLondon** [comment]
@crack00r 
Nothing yet, due to the nonce errors (Number ONCE, not the english slang.. 🤣 ) it loses track of placed orders so they cant be adjusted later on.
I am botting on DOGE with a % increase / decrease of 0.5 (so it always goes 1 satoshi either side of current price) and manually cancelling out of date or out of range orders every hour or so.

It's doing ok, no complaints. Loads of errors though but at least it is placing orders!

I'll give an update after leaving it for 24hrs and see what's happened.

<img width="1257" alt="screen shot 2017-06-15 at 20 15 20" src="https://user-images.githubusercontent.com/17095036/27180742-659e4240-5207-11e7-8a4f-a90cb52244b9.png">

Also for this situation i set:
// avoid selling at a loss below this pct
c.max_sell_loss_pct = 0

Will help if the currency goes below what i bought it for and should minimalise losses.

**Comment by crack00r** [comment]
@CreativeBacon is there any feedback from @carlos8f ?
I mean its useless right now for Poloniex.
So much potential, and then this error :/

**Comment by FreshLondon** [comment]
it's only useless as it cant move bids, as shown above it's good on low satoshi currencies until this is fixed.

I'm not support so i dont have contact with @carlos8f - I'm merely an avid user!

**Comment by crack00r** [comment]
:D 
The question ist, is every user who use poloniex have the same problem, ore only we some users

**Comment by DeviaVir** [comment]
Duplicate of #193
