### ISSUE TITLE
cannot locate sim_result.html

### ISSUE THREAD

**Issue by chriscrutt** [DeviaVir/zenbot#295]
after each simulation with various currencies (using Poloniex exchange), it says "wrote sim_result.html", as it should. But I cannot find where it is, I've searched everywhere on my computer. Is it because I am using docker on mac?

**Comment by DeviaVir** [comment]
Yes, that is exactly why. The file is written to your docker instance, and only available there. In this case, you might want to mount app as a volume so you can reach the `sim_result.html` in that mount.

**Comment by chriscrutt** [comment]
shoot, im a little new to docker, how would i go about doing that on osx?

**Comment by nodevar** [comment]
if you are using **docker-compose up** simple add the directory you want to share in docker-
 compose.yml

like this:
```
server:
  build: .
  volumes:
    - ./conf.js:/app/conf.js
    - /Users/myUsername/Desktop/Zenbot-Sim:/app/simulations
  links:
```
The Path needs to be within the Docker --> Preferences --> File Sharing settings

The Doc says you can run commands like this: 

> docker run --rm --link zenbot_mongodb_1:mongodb -it zenbot_server ./zenbot.sh list-selectors 

Since this is creating a new instance connected to the previously created mongodb you need to add the share with the -v switch. like this: 

`run --rm -v /Users/myUsername/Desktop/Zenbot-Sim/:/app/simulations --link zenbottest_mongodb_1:mongodb -it zenbottest_server  ./zenbot.sh sim poloniex.BTC-USDT`

if you do exec to the previously started container you startet with docker-compose up, it will use the already existing mountpoint.

like this:
`docker exec -it zenbottest_server_1 ./zenbot.sh sim poloniex.BTC-USDT`

Remember you can create volumes using docker-compose without declaring them in the Dockerfile.
