### ISSUE TITLE
Question about dropping DB

### ISSUE THREAD

**Issue by BarnumD** [DeviaVir/zenbot#30]
I have a question regarding new versions and when you say it's 'Safe to drop your zenbrain DB before this update.'

Does this mean I should or must drop the database?  It takes my computer a day or two to resync - and I loose some historical data - especially for exchanges that don't support backfill.  I'd rather not drop if I can get away with it.

**Comment by carlos8f** [comment]
It's not required to drop it, so I don't say "you must" drop the db. But due to code changes, esp. recently shifting around the RSI calculation params, your old data might be obsolete, not trigger the trader correctly, or cause other unforseen issues. If you run into issues after updating, try dropping your db and re-running `run.sh`, which should restart the map/reduce from raw data.

I might create some CLI commands to help with the data management, and some additional options like saving the `thoughts` as raw data, which can be fed into the reducer at a later date or on a separate machine. In the mean time I recommend the `mongodump` and `mongorestore` utilities, with these you can backup and transfer your db around as you like.
