### ISSUE TITLE
Allow configuration of URL "secret"

### ISSUE THREAD

**Issue by carlos8f** [DeviaVir/zenbot#52]

**Comment by Labseb** [comment]
In your web server configuration you need to specify '0.0.0.0' as hostname otherwise it will start on an IPv6 address if available, not on IPv4
see: 
https://nodejs.org/api/net.html#net_server_listening
"server.listen([port][, hostname][, backlog][, callback])#

Added in: v0.1.90
Begin accepting connections on the specified port and hostname. If the hostname is omitted, the server will accept connections on any IPv6 address (::) when IPv6 is available, or any IPv4 address (0.0.0.0) otherwise. "

**Comment by InfoAddict** [comment]
I'd love it if you specify hostname like you can port.

**Comment by Labseb** [comment]
i find it !!
here is my new listen.js file: /zenbot/node_modules/motley/site/listen.js

module.exports = function container (get) {
  return function listen (cb) {
    get('site.server').listen(get('conf.site.port'), '0.0.0.0', cb)
  }
}

So now, you can verify with "netstat -lnt" that your web server work on IPv4 on 0.0.0.0 and you can see graph from an other computer ;)

**Comment by JFD3D** [comment]
Cool, I'll try this when I find some time. This is only for a local network right? Thanks!

**Comment by Labseb** [comment]
If you would like to change the web server port, modify it in /zenbot/plugins/server/command.json

"default": 3301 <-- replace here

**Comment by Labseb** [comment]
the best way it's to use a general config file to do it, but i'm not enough good in java to do it...

**Comment by JFD3D** [comment]
You mean JavaScript not Java right?

**Comment by Labseb** [comment]
Yes JavaScript, sorry ;)
