### ISSUE TITLE
How to programing Cancel Order feature in my own strategy?

### ISSUE THREAD

**Issue by phongtt3** [DeviaVir/zenbot#528]
I know i can create my own strategy and define buy / sell signal base on whatever indicators i want. But how can i programing something like "Refusing to buy at ..." ?
I can't place cancelOrder() function at onPeriod: function (s, cb) {...}

**Comment by KryptoNova** [comment]
It looks like everything necessary to cancel the order is contained within the "s" variable that is passed into the calculate and onPeriod methods.  There is a reference to the Exchange object as well as all of the past orders with their IDs.  However, I do not know the ramifications of doing so as I have no way of testing except when doing live trading.  Also, this seems rather risky as the "engine" will probably not be aware of the cancellation and still try to handle the pending sale.

It seems if a buy signal is sent, but there is still a pending sale that the engine should cancel for the pending order.  Is this something that zenbot already is supposed to do, but is not working?

**Comment by nedievas** [comment]
It is working. When you see buying/selling signal, you may press 'c' to cancel.

**Comment by KryptoNova** [comment]
Sorry, I may not have been clear @nedievas.
Using the manual controls, it works just fine.  However, when using the paper trade and the status is stuck in "buying" due to market conditions and then a "sell" signal is given, Zenbot continues to try to buy.

I only had this condition once, but it did raise a concern that a buy signal is essentially committed to unless a manual "c" is used.

Should Zenbot be canceling the open buy order when the signal goes from buying to sell or from selling to buy?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
