### ISSUE TITLE
ZenBot keeps buying high and selling low - what gives?

### ISSUE THREAD

**Issue by angelnero** [DeviaVir/zenbot#72]
Using the default RSI settings, lowered the wait times to 30 minutes; been running the bot for about 12 - 24 hours; it has executed roughly 7 trades... 

>    Size (BTC) - Price (USD) - Fee (USD)
> S  0.0727 ----- 605.54 ----- ≈ 0.1100
> S  0.0100 ----- 605.57 ----- ≈ 0.0151
> S  0.0551 ----- 606.11 ----- ≈ 0.0835
> B  0.0322 ----- 607.71 ----- ≈ 0.0489
> B  0.1301 ----- 607.34 ----- ≈ 0.1976
> S  0.0793 ----- 605.33 ----- ≈ 0.1200
> S  0.0951 ----- 605.38 ----- ≈ 0.1440

All the sells have executed low, while the 2 buys executed high.  Shouldn't this be reversed?  I'm losing money here.  What am I missing?

**Comment by JFD3D** [comment]
Did you run any successful simulations prior to changing the wait times? If so what ROI did you get? I have found that always running simulations after changing (any) settings is the best practice to ensure profitability. In your case you have only given zenbot 30 minutes in between actions so at most it has only 6 more RSI sample to calculate from, this is assuming you left rest of the RSI settings as I've posted below:

```
      rs.rsi_query_limit = 100 // RSI initial value lookback
      rs.rsi_periods = 26 // RSI smoothing factor
      rs.rsi_period = '5m' // RSI tick size
      rs.rsi_up = 65 // upper RSI threshold
      rs.rsi_down = 28 // lower RSI threshold
      rs.check_period = '1m' // speed to trigger actions at

```

It's worth noting that @carlos8f set those default wait times because he found them to be the most profitable for BTC-USD
