### ISSUE TITLE
What really does markdown_buy_pct and markup_sell_pct?

### ISSUE THREAD

**Issue by vitorego** [DeviaVir/zenbot#811]
Does anybody can explain what really does markdown_buy_pct and markup_sell_pct? 
Any example please?

Thanks.

**Comment by slashafk** [comment]
Hello,
For example :
markdown_buy_pct 0.48 is buying at the current market price - (0.48% of current market price )
markup_sell_pct 0.48 is selling at the current market price + (0.48% of current market price )

This enable a strategy with early signal (like trend_ema or neural) to not get executed on the first signal and follow the trend until execution.

This also allow to get price surge (down or up) and also means that you will buy or sell at 0,48% of the market, since most exchange fees are between 0% and 0,50% you are pretty sure that you will earn a profit on most trades.

**Comment by ether-btc** [comment]
oh, these two options replace the markup_pct option
very nice to have and well done!

**Comment by vitorego** [comment]
thanks for the explanation
