### ISSUE TITLE
order_type=taker and --markdown_buy_pct

### ISSUE THREAD

**Issue by vitorego** [DeviaVir/zenbot#861]
Hi guys,
It seems when we are combining market orders and markdown_buy_pct option the bot always buy with slippage:

```
2017-12-14 00:36:11 - buy order placed at 691.962 USD
2017-12-14 00:36:16 - order status: done
buy order completed at 2017-12-14 00:36:16:

0.05840284 ETH at 695.400 USD
total 40.6133 USD
0.4968% slippage (orig. price 691.962 USD)
execution: a few seconds
```
When using taker/market orders the bot should wait until the market price hits the markdown_buy_pct. 

What do you think? Does it make sense to buy on the first signal when markdown_buy_pct is defined and we are using market/taker orders?

**Comment by slashafk** [comment]
Hello,
Since the taker order follow market price, it buy/sell without caring about markdown/markup (in fact most exchanges' API ignore the price given in parameters on market (taker) orders).

The idea of the markup/markdown is that a period has a high and a low price. The price is moving inside those limits, the markdown enables you to buy at the lowest price and the markup to sell at the highest price thanks to the slippage ... this is the intented behaviour ;).

(Some trader call such method scalping : buy at the beginning of the period at the low and sell before the end of the period at the high).

**Comment by vitorego** [comment]
ok. thanks
